TurboPack/Models/ErrorViewModel.cs
namespace TurboPack.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TurboPack/Models/Turbo.cs
namespace TurboPack.Models
{
    public class Turbo
    {

        public int Id { get; set; }

        public string Imagen { get; set; }

        public string Nombre { get; set; }

        public string Descripcion { get; set; }

        public string Ciudad { get; set; }


        public string sexo { get; set; }    

        public string Correo { get; set; }

        public List<object> Turbos { get; set; }
    }
}

TurboPack/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TurboPack.Models;

namespace TurboPack.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TurboPack/Controllers/TurboController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;

namespace TurboPack.Controllers
{
    public class TurboController : Controller
    {
        //public ActionResult TurboGet()
        //{
        //    Models.Turbo turbo = new Models.Turbo();
        //    using (var client = new HttpClient())
        //    {


        //        var resdponsetask = client.GetAsync("https://randomuser.me/api/");
        //        resdponsetask.Wait();
        //        var result = resdponsetask.Result;

        //        if (result.IsSuccessStatusCode)
        //        {
        //            var readTask = result.Content.ReadAsStringAsync();
        //            dynamic resultJSON = JObject.Parse(readTask.Result.ToString());
        //            readTask.Wait();
        //            turbo.Turbos = new List<object>();
        //            foreach (var resultitem in resultJSON.results)
        //            {
        //                Models.Turbo turboItems = new Models.Turbo();

        //                turboItems.sexo = resultitem.gender;
        //                turboItems.Nombre = resultitem.first;
        //                turboItems.Imagen = resultitem.medium;
        //                turboItems.Correo = resultitem.email;
        //                turboItems.Ciudad = resultitem.city;
        //                turbo.Turbos.Add(turboItems);
        //            }

        //        }

        //    }
        //    return View(turbo);
        //}

        [HttpGet]
        public ActionResult GetAll()
        {
            return View();

        }
    }
}

TurboPack/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TurboPack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TurboPack</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TurboPack.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TurboPack</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Turbo" asp-action="GetAll">Random</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TurboPack - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TurboPack/Views/Turbo/GetAll.cshtml
@model TurboPack.Models.Turbo
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>GetAll</h1>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Randoms:</h2>
            <hr />
        </div>

    </div>

</div>
<br />

<div class="container">
    <div class="row">
        <div class="col-md-1" style="padding-left:100px">
            <button type="button" class="btn btn-success" id="btnAdd" onclick="GetAll()">Agregar</button>
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-12">
            <table id="Table" class="table table-hover" border="1">
                <thead>
                    <tr>
                      
                        <th class="text-center" scope="col">Foto</th>
                        <th class="text-center" scope="col">Nombre </th>
                        <th class="text-center" scope="col">Sexo</th>
                        <th class="text-center" scope="col"> Email</th>
                        <th class="text-center" scope="col"> Direccion</th>
                
                      
                    </tr>

                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>

</div>




<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="/js/turbo.js"></script>            

TurboPack/Views/Turbo/TurboGet.cshtml
@model TurboPack.Models.Turbo
@{
    ViewData["Title"] = "TurboGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>TurboGet</h1>

@if (Model.Turbos != null)
{
    //tabla
    <table class="table table-bordered table-responsive">
        <thead>
            <tr>
               

                
                <td class="text-center" style=" font-weight:bold;">Nombre</td>
                <td class="text-center" style=" font-weight:bold;">Cuidad</td>
                <td class="text-center" style=" font-weight:bold;">Correo</td>
                <td class="text-center" style=" font-weight:bold;">sexo</td>



               
            </tr>
        </thead>

        <tbody>
            @foreach (TurboPack.Models.Turbo turbo in Model.Turbos)
            {
                <tr>


                    <td>@turbo.Nombre</td>
                    <td>@turbo.Ciudad</td>
                    <td>@turbo.Correo</td>
                    <td>@turbo.sexo</td>

                
                </tr>
            }
        </tbody>
    </table>


}
else
{
    <div class="alert alert-danger" role="alert">Ocurrio un error al realizar la consulta </div>
}